projects:
  ItemRecommender:
    schemaPath: app/src/main/graphql/schema.json
    includes:
    - app/src/main/graphql/**/*.graphql
    excludes:
    - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: ''
        generatedFileName: ''
        docsFilePath: app/src/main/graphql/com/amazonaws/amplify/generated/graphql
        graphQLApiId: n4wn7oypg5aktj5veph67vsm54
      endpoints:
        prod: >-
          https://su33scykjfdsbiz2qz4bsrbcqm.appsync-api.eu-west-1.amazonaws.com/graphql
